= INSTRUMENTA AUXILIARIS
:author: Oscar Guillermo Castro Jr.
:revdate: November 21st, 2019
:revnum: 1.0.0

This repository contains various PowerShell (Core) tools used through my .NET projects.

== Build-PSCorePsm1Module
Utilizing my project directory structure, this 'builds' a simple PowerShell Module (PSM1) project. The module copies source code into a build folder. Its inception comes from the idea of facilitating publication of PSM1 projects into Github Packages (previously Github Package Registry).

== Get-Version
Tool used for getting the version of some project, tool, or artifact. Currently only supports csproj files.

== Start-ProgressBarredSleep
Same as start-sleep but this function also shows a progress indicating the time remaining in the start-sleep function.

== ConvertTo-Nupkg
In an attempt to improve the upload method of powershell Nupkgs to Github Packages, this method attempts to facilitate that use case by helping convert PSM1 styled projects to nupkgs through the help of Publish-Module.
This is essentially a wrapper around Publish-Module.

== Publish-NugetGithubPackage
In 2019, Github Packages, formerly Github Package Registry, did not properly support cross platform nuget use cases. As a result, this is a work around by utilizing the Github Packages REST api to upload a nupkg.

== Add-NuspecRepositoryTag
Adds the proper repository tag to nuspec